#Versions of services from Bundle. Don't update this file manually.
#Tue Sep 01 07:41:10 UTC 2026
bundle.product.name=YouTrack
previously-started-product-version=2026.2.18194
service.hub.previously-started-version=2026.2.52366
service.youtrack.previously-started-version=2026.2.18194
